<table class="table table-hover table-bordered">
<thead>
	<tr>
		<th>Title</th>
		<th>Description</th>
		<th>Address</th>
		<th>Town</th>
		<th>County</th>
		<th>Country</th>
		<th>State</th>
		<th>Facilities</th>
	</tr>
</thead>
<tbody>
		<tr>	
		<td>{{$_property->title}}</td>
		<td>{{$_property->description}}</td>
		<td>{{$_property->address}}</td>
		<td>{{$_property->town}}</td>
		<td>{{$_property->county}}</td>
		<td>{{$_property->country}}</td>
		<td>{{$_property->state->name}}</td>
		<td>
			@foreach ($_property->facilities as $_facility)
				{{$_facility->name}}
			@endforeach
		</td>
</tbody>
</table>